-- tickets schema (spec: specs/database.md). Requires PostgreSQL 18 for the
-- native uuidv7() default: chronologically ordered UUIDs, so ids sort by
-- creation without a separate sequence. Dropped + recreated by test-db.mjs
-- (applySchemaAndSeed) for idempotent per-run resets.
-- messages drops first: it references tickets, so it must go before the parent
-- (DROP … CASCADE would work too, but explicit child-first keeps the intent).
-- sessions references users, so it drops before users for the same reason.
-- passkeys also references users, so it drops before users too.
DROP TABLE IF EXISTS passkeys;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS user_views;
DROP TABLE IF EXISTS ticket_events;
DROP TABLE IF EXISTS ticket_labels;
DROP TABLE IF EXISTS labels;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS tickets;

-- auth (spec: specs/auth-db.md). users holds credentials (scrypt "salt:hexhash"
-- in password_hash); only the public shape (id/email/name/role) ever leaves the
-- API. sessions is the shared sid → user_id store that replaces the old
-- in-memory Map, so a login survives a process restart and any app instance
-- resolves the same sid. id is an explicit uuid (seed pins fixed v7 literals);
-- unlike tickets it does not default to uuidv7() — users are seeded, not created
-- at runtime.
CREATE TABLE users (
  id uuid PRIMARY KEY,
  email text NOT NULL UNIQUE,
  name text NOT NULL,
  role text NOT NULL CHECK (role IN ('agent', 'customer')),
  password_hash text NOT NULL, -- scrypt: "salt:hexhash"
  created_at timestamptz NOT NULL DEFAULT now()
);

-- sessions: sid → user_id. sid is a runtime crypto.randomUUID() (v4 — an opaque
-- secret token, no ordering needed), so no uuidv7() default. ON DELETE CASCADE
-- so removing a user takes their sessions with it.
CREATE TABLE sessions (
  sid uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- passkeys: WebAuthn credentials (spec: specs/passkey.md). One user may hold
-- several passkeys, so only credential_id is UNIQUE (not user_id) — this also
-- keeps E2E retries stable when a re-run registers a fresh key for the same
-- seed user. ON DELETE CASCADE so removing a user takes their passkeys with it.
-- credential_id / public_key are base64url text; counter guards against cloned
-- authenticators (verifyAuthenticationResponse returns the next value).
CREATE TABLE passkeys (
  id uuid PRIMARY KEY DEFAULT uuidv7(),
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  credential_id text NOT NULL UNIQUE,
  public_key text NOT NULL,
  counter bigint NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ticket-model (spec: specs/ticket-model.md). number is a 1-based human handle
-- rendered as SUP-${number} by the web layer; GENERATED BY DEFAULT AS IDENTITY
-- so seeds insert in order (1..3) without pinning it and new rows continue from
-- there — the spec allows gaps/reuse and only guarantees UNIQUE. assignee_email
-- is NULL when unassigned; updated_at is bumped to now() on the mutations the
-- spec lists (reply / setStatus / setAssignee / setLabels).
CREATE TABLE tickets (
  id uuid PRIMARY KEY DEFAULT uuidv7(),
  number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  subject text NOT NULL CHECK (char_length(subject) BETWEEN 1 AND 200),
  status text NOT NULL CHECK (status IN ('open', 'in_progress', 'resolved')),
  priority text NOT NULL CHECK (priority IN ('low', 'medium', 'high')),
  requester_email text NOT NULL,
  assignee_email text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- messages: the conversation thread on a ticket (spec: specs/ticket-detail.md).
-- FK ON DELETE CASCADE so a deleted ticket takes its thread with it; CHECKs
-- mirror the zod input layer (author_role enum, body 1..2000) so a raw INSERT
-- that bypasses zod still can't write an invalid row.
CREATE TABLE messages (
  id uuid PRIMARY KEY DEFAULT uuidv7(),
  ticket_id uuid NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  author_email text NOT NULL,
  author_role text NOT NULL CHECK (author_role IN ('customer', 'agent')),
  body text NOT NULL CHECK (char_length(body) BETWEEN 1 AND 2000),
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ticket-model (spec: specs/ticket-model.md). labels is a fixed catalogue (the
-- colour lives server-side so the UI needs no change to render a swatch); the
-- CHECKs mirror the wire contract (name 1..32, colour #rrggbb). ticket_labels is
-- the many-to-many join; ticket_events is the activity log whose payload jsonb
-- is byte-for-byte the wire TicketEvent payload.
CREATE TABLE labels (
  id uuid PRIMARY KEY DEFAULT uuidv7(),
  name text NOT NULL UNIQUE CHECK (char_length(name) BETWEEN 1 AND 32),
  color text NOT NULL CHECK (color ~ '^#[0-9a-f]{6}$')
);
CREATE TABLE ticket_labels (
  ticket_id uuid NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  label_id uuid NOT NULL REFERENCES labels(id) ON DELETE CASCADE,
  PRIMARY KEY (ticket_id, label_id)
);
CREATE TABLE ticket_events (
  id uuid PRIMARY KEY DEFAULT uuidv7(),
  ticket_id uuid NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  actor_email text NOT NULL,
  type text NOT NULL CHECK (type IN ('status_changed', 'assignee_changed', 'labels_changed', 'priority_changed')),
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- saved-views (spec: specs/saved-views.md). A named filter combination an agent
-- saves for their own /tickets; scoped by user_email (no FK — the owner is the
-- session email, matching requester_email/assignee_email's plain-text style).
-- filters is the wire SavedViewFilters jsonb stored verbatim; UNIQUE
-- (user_email, name) makes a same-name save a CONFLICT the router maps.
CREATE TABLE user_views (
  id uuid PRIMARY KEY DEFAULT uuidv7(),
  user_email text NOT NULL,
  name text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 32),
  filters jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_email, name)
);
